#!/usr/bin/python
import os
import sys
import argparse
import textwrap
import numpy as np
from skimage import io
import skimage.transform
from skimage.color import rgb2gray

#    Copyright (C) 2015, Asher Bender
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# -----------------------------------------------------------------------------
#                               Script Constants
# -----------------------------------------------------------------------------

# Characters available for ASCII art.
#
#     ~ !"#$%&'()*+,-./0123456789:;<=
#     >?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]
#     ^_`abcdefghijklmnopqrstuvwxyz{|}
#
CHARS = np.array([126, ] + range(32, 62) + range(62, 94) + range(94, 126))

# Hard-coded perceptual luminance for ASCII characters.
CHAR_LUMINANCE = np.array([0.286 , 0.    , 0.4   , 0.2372, 0.8726, 0.7619, 0.6703,
                           0.8285, 0.1182, 0.4071, 0.4082, 0.3452, 0.4034, 0.1594,
                           0.105 , 0.0943, 0.393 , 0.8866, 0.5729, 0.6595, 0.6895,
                           0.715 , 0.7202, 0.8348, 0.5213, 0.9029, 0.8347, 0.1881,
                           0.2531, 0.4249, 0.4432, 0.425 , 0.4503, 1.    , 0.7863,
                           0.9914, 0.5933, 0.8796, 0.7962, 0.6399, 0.7805, 0.8587,
                           0.633 , 0.5692, 0.8326, 0.5232, 0.9939, 0.99  , 0.8496,
                           0.7567, 0.9118, 0.9028, 0.7209, 0.5663, 0.7936, 0.6806,
                           0.9691, 0.7229, 0.5608, 0.7121, 0.4963, 0.393 , 0.4963,
                           0.2565, 0.1201, 0.0817, 0.6916, 0.7858, 0.4655, 0.7853,
                           0.6732, 0.5228, 0.866 , 0.6904, 0.482 , 0.5152, 0.6896,
                           0.4605, 0.7789, 0.5899, 0.642 , 0.7846, 0.7862, 0.3867,
                           0.5409, 0.5098, 0.5893, 0.4972, 0.6749, 0.5276, 0.6201,
                           0.5132, 0.5521, 0.4324, 0.5459])

# -----------------------------------------------------------------------------
#                               Script Functions
# -----------------------------------------------------------------------------

def scale_image(img, rescaled_width=80, char_ratio=2.):
    """Scale input image and correct for ASCII character aspect-ratio.

    Args:
      img (np.array): (M, N) grey-scale image.
      rescaled_width (int, *optional*): width of output image in
          pixels/characters.
      char_ratio (float, *optional*): Height:width ratio of ASCII characters.

    Returns:
      np.array: (I, J) re-scaled image.

    """

    # Get size of image.
    height, width = img.shape

    # Calculate height of re-scaled image in pixels (preserving aspect ratio).
    rescaled_height = float(height * rescaled_width) / float(width)

    # Account for non-square ASCII characters by adjusting the aspect ratio.
    rescaled_height = int(rescaled_height / char_ratio)

    # Re-scale image.
    return skimage.transform.resize(img,
                                    (rescaled_height, rescaled_width),
                                    clip=True)


def bin_luminance(bins, characters, luminance):
    """Arrange characters in to luminance bins.

    Note: Empty bins will be removed from the output.

    Args:
      bins (int): number of evenly spaced luminance bins to use.
      characters (np.array): (M,) characters available for rendering (as
          integers).
      luminance (np.array): (M,) perceptual luminance of characters.

    Returns:
      tuple: (edges, choices) where ``edges`` is an array defining the
          luminance bin edges and ``choices`` is a list of numpy arrays. Each
          array in ``choices`` represents the set of ASCII characters
          associated with each luminance bin.

    """

    # Bin character luminance into discrete levels.
    counts, edges = np.histogram(luminance, bins=bins)

    # Remove bins with zero observations.
    t = [(count, edge) for count, edge in zip(counts, edges) if count > 0]
    counts, edges = zip(*t)
    counts = list(counts)
    edges = list(edges)

    # Make the lightest luminance a category of its own (so white backgrounds
    # are not randomised).
    sorted_luminance = np.sort(luminance)
    if counts[0] > 1:
        counts.insert(0, 1)
        counts[1] -= 1
        edges.insert(1, 0.75 * sorted_luminance[1])

    # Determine which bin the character/luminance belong to.
    #
    # Note: bins without characters were removed. Approximate these values by
    #       assigning pixels to the nearest bin that has characters.
    edges = np.array(edges)
    luminance_bin = np.digitize(luminance, edges)

    # Create list of choices for each bin.
    choices = list()
    for i in range(1, len(counts) + 1):
        choices.append(characters[luminance_bin == i])

    return edges, choices


def grayscale_to_ascii(img, characters=CHARS, luminance=CHAR_LUMINANCE,
                       bins=None, boarder=False):
    """Convert image pixels to ASCII characters.

    Args:
      img (np.array): (M, N) grey-scale image.
      characters (np.array, *optional*): (M,) characters available for
          rendering (as integers).
      luminance (np.array, *optional*): (M,) perceptual luminance of
          characters.
      bins (int, *optional*): Number of luminance levels to use during
          rendering. If binning is enabled, the characters are arranged into a
          number of perceptual luminance bins. ASCII art is then generated by
          assigning each pixel to a luminance bin and drawing a random
          character from the bin.
      boarder (bool, *optional*): If set to True, a boarder will be added to
          the image.

    Returns:
      str: ASCII art representation of input image.

    """

    # Reshape image and luminance vector into arrays.
    rows, cols = img.shape
    pixels = img.flatten().reshape((1, img.size))
    luminance = luminance.reshape((1, luminance.size))

    # Bin pixel into luminance bin.
    if bins:
        edges, choices = bin_luminance(bins, characters, luminance.flatten())

        # Find closest bin.
        edges = edges.reshape((1, len(edges)))
        nearest_bin = np.abs(edges.T - pixels).argmin(axis=0)

        # Iterate through bins.
        ascii_matrix = np.zeros(nearest_bin.shape, dtype=np.int64)
        for i in range(len(choices)):
            idx = nearest_bin == i
            if len(choices[i]) == 1:
                ascii_matrix[idx] = choices[i]
            else:
                ascii_matrix[idx] = np.random.choice(choices[i],
                                                     size=idx.sum(),
                                                     replace=True)

        # Reshape matrix back to image dimensions.
        ascii_matrix = ascii_matrix.reshape((rows, cols))

    # Bin pixels into nearest registered luminance.
    else:
        idx = np.abs(luminance.T - pixels).argmin(axis=0).reshape((rows, cols))

        # Convert luminance to ASCII characters.
        ascii_matrix = characters[idx].reshape((rows, cols))

    # Initialise ASCII art.
    if boarder:
        ascii_art = '+' + cols * '-' + '+\n'
    else:
        ascii_art = ''

    # Convert matrix to string.
    for i in range(rows):
        row = ''.join(unichr(c) for c in ascii_matrix[i, :])
        if boarder:
            row = '|' + row + '|'

        ascii_art += row + '\n'

    if boarder:
        ascii_art += '+' + cols * '-' + '+\n'

    return ascii_art


# -----------------------------------------------------------------------------
#                                    Script
# -----------------------------------------------------------------------------
if __name__ == "__main__":

    # -------------------------------------------------------------------------
    #         Configure command-line options & parsing behaviour
    # -------------------------------------------------------------------------

    man = """Convert image into ASCII art."""
    formatter_class = argparse.RawDescriptionHelpFormatter
    parser = argparse.ArgumentParser(formatter_class=formatter_class,
                                     description=textwrap.dedent(man))

    # Image argument.
    parser.add_argument('image', type=str, nargs='?', help='Path to image.')

    # Width.
    msg = 'Width of ASCII art in characters.'
    parser.add_argument('-w', '--width', metavar='[int]', help=msg, type=int,
                        default=80)

    # Luminance levels/bins.
    msg = """By default ASCII art is generated by allocating each pixel to the nearest
    character based on the characters' perceptual luminance. If binning is
    enabled, the characters are arranged into a number of perceptual luminance
    bins. ASCII art is then generated by assigning each pixel to a luminance
    bin and drawing a random character from the bin. Levels must be an integer
    between 5 and 50."""
    parser.add_argument('-l', '--levels', metavar='[int]', help=msg, type=int,
                        default=None)

    # Character ratio.
    msg = """Height:width ratio per ASCII character. The ratio must be greater
    than or equal to one (square characters)."""
    parser.add_argument('-r', '--ratio', metavar='[float]', help=msg,
                        type=float, default=2)

    # Image boarder.
    parser.add_argument('-b', '--boarder', action='store_true', default=False,
                        help='Add boarder to ASCII art.')

    # Print character set.
    msg = """Print character set with perceptual luminance and exit. If binning
    has been enabled, each luminance level and its associated characters will
    be printed."""
    parser.add_argument('--list', action='store_true', default=False, help=msg)

    # -------------------------------------------------------------------------
    #                  Get arguments from the command-line
    # -------------------------------------------------------------------------
    args = parser.parse_args()

    # Ensure the number of luminance bins is valid.
    if (args.levels is not None) and ((args.levels < 5) or (args.levels > 50)):
        raise Exception("'--bins' must be greater 5 and less than 50.")

    # Print characters and exit.
    if args.list:
        if args.levels:
            char_set = zip(*bin_luminance(args.levels, CHARS, CHAR_LUMINANCE))
        else:
            char_set = sorted(zip(CHAR_LUMINANCE, CHARS), key=lambda t: t[0])

        for luminance, character in char_set:
            if isinstance(character, int):
                string = unichr(character)
            else:
                string = ''.join([unichr(c) for c in character])
            print '%1.4f: %s' % (luminance, string)

        sys.exit()

    # Ensure the image file exists.
    if not os.path.isfile(args.image):
        msg = "The image '%s' does NOT exist."
        raise IOError(msg % args.image)

    # If the boarder has been enabled, make the image slightly smaller so that
    # the final output is the specified width.
    if args.boarder:
        args.width -= 2

    # Ensure the width is valid.
    if args.width < 2:
        raise Exception("'--width' must be greater than or equal to two.")

    # Ensure the height:width ratio is valid.
    if args.ratio < 1:
        raise Exception("'--ratio' must be greater than or equal to one.")

    # -------------------------------------------------------------------------
    #                      Convert image into ASCII
    # -------------------------------------------------------------------------
    character_width = 1
    character_height = args.ratio

    # Load image and convert to grey-scale.
    #
    # Note: the 'as_grey' option in io.imread does not appear to work on all
    #       images.
    #
    img = io.imread(args.image)
    if img.shape == (2,):
        img = rgb2gray(img[0])
    else:
        img = rgb2gray(img)

    # Invert grey-scale: zero is white, one is black.
    img = 1. - img

    # Re-scale image width to number of characters specified. Preserve aspect
    # ratio.
    rescaled_img = scale_image(img, rescaled_width=args.width,
                               char_ratio=args.ratio)

    # Convert mean luminance image into ASCII art.
    ascii_art = grayscale_to_ascii(rescaled_img,
                                   characters=CHARS,
                                   luminance=CHAR_LUMINANCE,
                                   bins=args.levels,
                                   boarder=args.boarder)

    print ascii_art
